# Generated by Django 5.0 on 2023-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default=True, max_length=500, null=True),
        ),
    ]
