# Generated by Django 5.0 on 2023-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0002_product_time_alter_product_date_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
