# Generated by Django 5.0 on 2023-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
